= Infinispan Feed Provider

This project acts as `Provider Service` that helps in implementing OpenWhisk Feeds
via https://github.com/apache/incubator-openwhisk/blob/master/docs/feeds.md#implementing-feeds-via-connections[Connections]

In this demo provider service registers Infinispan Remote ClientCacheListener as
a event source to OpenWhisk triggers. When ever a Cache Entry is created/deleted/updated
this Feed will fire all the associated Triggers with event data as payload.

Refer to the following links for more information on Triggers, Rules and Feeds

* https://github.com/apache/incubator-openwhisk/blob/master/docs/triggers_rules.md[Triggers and Rules]
* https://github.com/apache/incubator-openwhisk/blob/master/docs/feeds.md[Feeds]

[[pre-req]]
= Pre-requisite

* Deploy https://github.com/infinispan/infinispan-openshift-templates[Infinispan on OpenShift]
* Deploy https://github.com/kameshsampath/openwhisk-openshift#installing-on-minishift[OpenWhisk on Minishift]

[IMPORTANT]
====
* For all the CLI commands to work as it is, deploy OpenWhisk to a OpenShift Project
called `openwhisk`
* Deploy applications infinispan and infinispan-feed-provider to `myproject` workspace
* make user `developer` as admin for both these projects via
[code,sh]
----
 oc adm policy add-role-to-user admin developer -n openwhisk
----
====

[[build-and-deploy]]
== Build and Deploy

[code,sh]
----
mvn clean package fabric8:deploy
----

[IMPORTANT]
====
Whenever you update the code, as current trigger store is ephemeral, its
ideal recreate the triggers to add it to the store
====