kind: "Deployment"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
         - name: JAVA_OPTIONS
           value: -XX:ThreadStackSize=256k -Xms64m -Xmx128m
         - name: JAVA_MAX_MEM_RATIO
           value: 13
         - name: AB_JOLOKIA_OFF
           value: "true"
         - name: AB_OFF
           value: "true"
         - name: COUCHDB_USER
           valueFrom:
             secretKeyRef:
               name: db.auth
               key: db_username
         - name: COUCHDB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: db.auth
               key: db_password
         - name: TRIGGERSTORE_SERVICE_HOST
           value: "$(COUCHDB_SERVICE_HOST)"
         - name: TRIGGERSTORE_SERVICE_PORT
           value: "$(COUCHDB_SERVICE_PORT_COUCHDB)"
